- name: Webserver Started
  hosts: webservers
  become: yes
  tasks:
    - name: Installing httpd
      ansible.builtin.yum:
        name: httpd
        state: present

    - name: Starting httpd
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes

- name: DBserver Started
  hosts: dbservers
  become: yes
  tasks:
    - name: Installing mariadb
      ansible.builtin.yum:
        name: mariadb
        state: present
