- name: Webserver Started
  hosts: webservers
  become:	yes
  tasks:	
    - name:	Installing httpd
      ansible.builtin.yum:
        name:	httpd
        state:	present
    - name:	Starting httpd
      ansible.builtin.service:
        name:	httpd
        state:	started
        enabled:	yes
    - name: Copying Files
      ansible.builtin.copy:
        src: index.html
        dest: /var/www/html/index.html
        backup: yes
